spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/files/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
