server:
  port: 8082

spring:
  application:
    name: auth-service


  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: Password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    appname: auth-service
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
